#! /bin/bash
set -o errexit

TOOLS_DIR=${HOME}/.tools-engineering

TOOLS_ARTIFACTORY=https://artifactory.tools.springer-sbm.com/api/pypi/tools-pypi/simple
DOCKER_ENV_VENV=${TOOLS_DIR}/docker-env
if [ ! -f ${DOCKER_ENV_VENV}/bin/python ]; then
    python3 -m venv $DOCKER_ENV_VENV --copies
    ${DOCKER_ENV_VENV}/bin/python -m pip install --upgrade pip
fi

if ! ${DOCKER_ENV_VENV}/bin/python -c "from docker_env.__main__ import *" 2>/dev/null; then
    ${DOCKER_ENV_VENV}/bin/python -m pip install te-docker-env --upgrade --extra-index-url=$TOOLS_ARTIFACTORY
fi
${DOCKER_ENV_VENV}/bin/python -m docker_env "$@"
