# fly -t content_hub sp -p ml-deploy-docker -c pipeline.yml

resources:
- name: git
  type: git
  source:
    private_key: ((github.private_key))
    uri: git@github.com:springernature/ml-deploy

- name: ml-docker
  type: docker-image
  source:
    password: ((gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/marklogic
    username: _json_key

- name: ml-deploy
  type: docker-image
  source:
    password: ((gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/ml-deploy
    username: _json_key

- name: ml-docker-10
  type: docker-image
  source:
    password: ((gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/marklogic10
    username: _json_key

- name: ml-deploy-10
  type: docker-image
  source:
    password: ((gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/ml-deploy10
    username: _json_key

- name: ml-docker-8
  type: docker-image
  source:
    password: ((gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/marklogic8
    username: _json_key

- name: ml-deploy-8
  type: docker-image
  source:
    password: ((gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/ml-deploy8
    username: _json_key

jobs:
- name: MarkLogic 9
  plan:
  - get: git
    trigger: true
  - get: ml-docker
    trigger: true
    params:
      save: true
  - aggregate:
    - put: ml-deploy
      params:
        build: git
        load_base: ml-docker

- name: MarkLogic 10
  plan:
  - get: git
    trigger: true
  - get: ml-docker-10
    trigger: true
    params:
      save: true
  - aggregate:
    - put: ml-deploy-10
      params:
        build: git
        load_base: ml-docker-10
        build_args:
          ML_VERSION: 10

- name: MarkLogic 8
  plan:
    - get: git
      trigger: true
    - get: ml-docker-8
      trigger: true
      params:
        save: true
    - aggregate:
        - put: ml-deploy-8
          params:
            build: git
            load_base: ml-docker-8
            build_args:
              ML_VERSION: 8