# fly -t content_hub sp -p ml-deploy-docker -c pipeline.yml

resources:
- name: git
  type: git
  source:
    private_key: ((github.private_key))
    uri: git@github.com:springernature/ml-deploy
- name: ml-docker
  type: docker-image
  source:
    password: ((gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/marklogic
    username: _json_key
- name: ml-deploy
  type: docker-image
  source:
    password: ((gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/ml-deploy
    username: _json_key   

jobs:
- name: Docker
  plan:
  - get: git
    trigger: true
  - get: ml-docker
    trigger: true
    params:
      save: true
  - aggregate:
    - put: ml-deploy
      params:
        build: git
        load_base: ml-docker
