# fly -t content_hub sp -p ml-deploy-docker -c pipeline.yml
groups: []
resources:
- name: git
  type: git
  source:
    branch: halfpipe
    private_key: ((github.private_key))
    uri: git@github.com:springernature/ml-deploy
- name: ml-docker
  type: docker-image
  source:
    password: ((gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/marklogic
    username: _json_key
- name: Docker Registry
  type: docker-image
  source:
    password: ((gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/ml-deploy
    username: _json_key
resource_types: []
jobs:
- name: docker-push
  serial: true
  plan:
  - get: git
    trigger: true
  - get: ml-docker
    trigger: true
  - put: Docker Registry
    params:
      build: git

