# fly -t content_hub sp -p ml-deploy-docker -c pipeline.yml

resources:
- name: git
  type: git
  source:
    private_key: ((halfpipe-github.private_key))
    uri: git@github.com:springernature/ml-deploy

- name: ml-docker-11
  type: docker-image
  source:
    password: ((halfpipe-gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/marklogic11
    username: _json_key

- name: ml-deploy-11
  type: docker-image
  source:
    password: ((halfpipe-gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/ml-deploy11
    username: _json_key

- name: ml-docker-10
  type: docker-image
  source:
    password: ((halfpipe-gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/marklogic10
    username: _json_key

# Default `ml-deploy` docker image to use ML-10
- name: ml-deploy-10
  type: docker-image
  source:
    password: ((halfpipe-gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/ml-deploy
    username: _json_key

- name: ml-docker-8
  type: docker-image
  source:
    password: ((halfpipe-gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/marklogic8
    username: _json_key

- name: ml-deploy-8
  type: docker-image
  source:
    password: ((halfpipe-gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/ml-deploy8
    username: _json_key

- name: ml-docker-9
  type: docker-image
  source:
    password: ((halfpipe-gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/marklogic9
    username: _json_key

- name: ml-deploy-9
  type: docker-image
  source:
    password: ((halfpipe-gcr.private_key))
    repository: eu.gcr.io/halfpipe-io/ml-deploy9
    username: _json_key

jobs:
- name: MarkLogic 9
  plan:
  - get: git
    trigger: true
  - get: ml-docker-9
    trigger: true
    params:
      save: true
  - aggregate:
    - put: ml-deploy-9
      params:
        build: git
        load_base: ml-docker-9
        build_args:
          ML_VERSION: 9

- name: MarkLogic 10
  plan:
  - get: git
    trigger: true
  - get: ml-docker-10
    trigger: true
    params:
      save: true
  - aggregate:
    - put: ml-deploy-10
      params:
        build: git
        load_base: ml-docker-10
        build_args:
          ML_VERSION: 10

- name: MarkLogic 11
  plan:
    - get: git
      trigger: true
    - get: ml-docker-11
      trigger: true
      params:
        save: true
    - aggregate:
        - put: ml-deploy-11
          params:
            build: git
            load_base: ml-docker-11
            build_args:
              ML_VERSION: 11

- name: MarkLogic 8
  plan:
    - get: git
      trigger: true
    - get: ml-docker-8
      trigger: true
      params:
        save: true
    - aggregate:
        - put: ml-deploy-8
          params:
            build: git
            load_base: ml-docker-8
            build_args:
              ML_VERSION: 8